# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76186bca600ba561aa75a866fae8c5a9ee963e29d0e1b120625f55d749aa7afab17bd5b5d14d7a66326128bba406447e78da469402165b0f8d49a3a12e13146d

test:
  secret_key_base: 0c0ce0a5530edd7a734105be71785a91c532ab490f45cd5ba3e3359e19ebdc353bfa550daf8a1964e4e309404e218b1822af720766d6a5c4a9897f9e57be1e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
